# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version.
VAGRANTFILE_API_VERSION = "2"

# | Vagrant
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|


    # | global

        # base - box
        config.vm.box = "ubuntu/xenial64"

        # network - adapter - bridged
        config.vm.network "public_network"

        # copy - app / ssh / system
        config.vm.provision "file", source: "../app",       destination: "/tmp/app"
        config.vm.provision "file", source: "system",       destination: "/tmp/system"

        # provision - shell - bash
        config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
        config.vm.provision "shell", path: "script/provision"

        # share - vagrant - disable
        config.vm.synced_folder '.', '/vagrant', disabled: true

        # ssh - agent - fowarding
        config.ssh.forward_agent = true

        # | VirtualBox
        config.vm.provider "virtualbox" do |vb|

            # VBoxManage - settings
            vb.customize [
                "modifyvm", :id,
                "--memory", "400",
            ]

        end
        # VirtualBox |

    # global |


    # | machine(s)

        # | miv
        config.vm.define "miv" do |web|
            config.vm.hostname = "miv"
            config.vm.provider :virtualbox do |vb|
                vb.name = "miv"
            end
        end
        # miv |

        # | build-miv
        config.vm.define "build-miv" do |web|
            config.vm.hostname = "build-miv"
            config.vm.provider :virtualbox do |vb|
                vb.name = "build-miv"
            end
        end
        # build-miv |

        # | build
        config.vm.define "build" do |web|
            config.vm.hostname = "build"
            config.vm.provider :virtualbox do |vb|
                vb.name = "build"
            end
        end
        # build |

        # | home
        config.vm.define "home" do |web|
            config.vm.hostname = "home"
            config.vm.provider :virtualbox do |vb|
                vb.name = "home"
            end
        end
        # home |

        # | learn
        config.vm.define "learn" do |web|
            config.vm.hostname = "learn"
            config.vm.provider :virtualbox do |vb|
                vb.name = "learn"
            end
        end
        # learn |

        # | media
        config.vm.define "media" do |web|
            config.vm.hostname = "media"
            config.vm.provider :virtualbox do |vb|
                vb.name = "media"
            end
        end
        # media |

        # | network
        config.vm.define "network" do |web|
            config.vm.hostname = "network"
            config.vm.provider :virtualbox do |vb|
                vb.name = "network"
            end
        end
        # network |

        # | stream
        config.vm.define "stream" do |web|
            config.vm.hostname = "stream"
            config.vm.provider :virtualbox do |vb|
                vb.name = "stream"
            end
        end
        # stream |

        # | system
        config.vm.define "system" do |web|
            config.vm.hostname = "system"
            config.vm.provider :virtualbox do |vb|
                vb.name = "system"
            end
        end
        # system |

    # machine(s) |


end
# Vagrant |
