#!/bin/bash
#
#   curl - test - ajax - create - url - bad - data
#




    # src
    source "`dirname $0`/miv"
    source "`dirname $0`/ajax-create-url"

    # curl
    curl "$miv_curl" -X "$miv_http_request_method"  \
        "$miv_http_address" $@                      \
        --data "request_method=$miv_request_method&url=http://example.com/"




#
#   curl - test - ajax - create - url - bad - data
#
