#!/bin/bash
#
#   curl - test - ajax - create - url - bad - data
#




    # src
    source "`dirname $0`/.config-ajax-miv"
    source "`dirname $0`/.config-ajax-get-url"

    # curl
    curl "$miv_curl" -X "$miv_http_request_method"  \
        "$miv_http_address" $@                      \
        --data "request_method=$miv_request_method"




#
#   curl - test - ajax - create - url - bad - data
#
