#!/bin/bash
#
#   curl - test - ajax - read - config - 200
#




    # variable(s)
    miv_curl="--verbose"
    miv_object='config'
    miv_method='read'
    miv_data="key=flag_locked"
    miv_url="build-miv/api.php?object=$miv_object&method=$miv_method"

    # curl
    curl "$miv_curl"                                \
        --data "$miv_data"                          \
        "$miv_url"                                  \
        $@




#
#   curl - test - ajax - read - config - 200
#
