#!/bin/bash
#
#   curl - test - ajax - read - urls
#




    # src
    source "`dirname $0`/config-ajax-miv"
    source "`dirname $0`/config-ajax-read-url"

    # curl
    curl "$miv_curl" -X "$miv_http_request_method"  \
        "$miv_http_address" $@                      \
        --data "request_method=$miv_request_method"




#
#   curl - test - ajax - read - urls
#
