#!/bin/bash
#
#   curl - test - ajax - img - read - 200
#




    # variable(s)
    miv_curl="--verbose"
    miv_object='img'
    miv_method='read_url_img'
    miv_data="id_url=1"
    miv_url="miv/api.php?object=$miv_object&method=$miv_method"

    # curl
    curl "$miv_curl"                                    \
        --header "Miv-Object: $miv_object"              \
        --header "Miv-Method: $miv_method"              \
        -F       "$miv_data"                            \
        "$miv_url"                                      \
        $@




#
#   curl - test - ajax - img - read - 200
#
