#!/bin/bash
#
#   curl - test - ajax - img - upload - 200
#




    # variable(s)
    miv_curl="--verbose"
    miv_object='img'
    miv_method='upload'
    miv_data="id_url=0"
    miv_url="miv/api.php?object=$miv_object&method=$miv_method"

    # curl
    curl "$miv_curl"                                    \
        --header "Miv-Object: $miv_object"              \
        --header "Miv-Method: $miv_method"              \
        -F       "file=@test-ajax-img-upload-200.jpg"   \
        -F       "$data"                                \
        "$miv_url"                                      \
        $@




#
#   curl - test - ajax - img - upload - 200
#
