#!/bin/bash
#
#   curl - test - ajax - create - msg - 400
#




    # src
    source "`dirname $0`/config-ajax-miv"
    source "`dirname $0`/config-ajax-create-msg"

    # curl
    curl "$miv_curl" -X "$miv_http_request_method"  \
        "$miv_http_address" $@                      \
        --data "request_method=$miv_request_method&code=9001&msg=curl-test"




#
#   curl - test - ajax - create - msg - 400
#
