#!/bin/bash
#
#   curl - test - ajax - read - msgs
#




    # variable(s)
    miv_curl="--verbose"
    miv_object='msg'
    miv_method='reads'
    miv_data=""
    miv_http_method='POST'
    miv_http_url='miv/dev/api.php'

    # curl
    curl "$miv_curl" -X "$miv_http_method"          \
        --header "Miv-Object: $miv_object"          \
        --header "Miv-Method: $miv_method"          \
        --data "$miv_data"                          \
        "$miv_http_url" $@




#
#   curl - test - ajax - read - urls
#
