#!/bin/bash
#
#   curl - test - ajax - read - msgs - 200
#




    # variable(s)
    miv_curl="--verbose"
    miv_object='msg'
    miv_method='reads'
    miv_data=""
    miv_url='miv/dev/api.php'

    # curl
    curl "$miv_curl"                                \
        --header "Miv-Object: $miv_object"          \
        --header "Miv-Method: $miv_method"          \
        --data "$miv_data"                          \
        "$miv_url"                                  \
        $@




#
#   curl - test - ajax - read - urls - 200
#
