#!/bin/bash
#
#   curl - test - ajax - img - upload - 200
#




    # variable(s)
    miv_curl="--verbose"
    miv_object='img'
    miv_method='upload'
    miv_data="id_url=0"
    miv_img='miv/api.php'

    # curl
    curl "$miv_curl"                                    \
        --header "Miv-Object: $miv_object"              \
        --header "Miv-Method: $miv_method"              \
        -F       "image=@test-ajax-img-upload-200.jpg"  \
        -F       "$miv_data"                            \
        "$miv_img"                                      \
        $@




#
#   curl - test - ajax - img - upload - 200
#
