#!/bin/bash
#
#   vagrant - script - provision
#




    # export - noninteractive
    export DEBIAN_FRONTEND=noninteractive
    set -x


    # | aptitude

        # apt - update
        apt-get update  -q

        # apt - upgrade
        apt-get upgrade -q -y

        # apt - install - lamp / git / realpath / tree
        apt-get install -q -y apache2 mysql-server php-mysql php libapache2-mod-php php-mcrypt git realpath tree

        # apt - cleanup
        apt-get autoremove

    # aptitude |




    # | app
    if [ -d '/tmp/app' ]; then

        # backup - img
        if [ -d '/var/www/webroot/img' ]; then
            rm -r '/tmp/app/webroot/img'
            mv    '/var/www/webroot/img' '/tmp/app/webroot/img'
        fi

        # remove existing
        [ -d '/var/www' ] && rm -rf '/var/www'

        # move
        mv '/tmp/app' '/var/www'

        # database - app/config
        cp '/var/www/config/database.php.sample' '/var/www/config/database.php'

        # ownership - app/www
        chown -R root:root '/var/www'
                      find '/var/www' -type f -exec chmod 644 {} \;
                      find '/var/www' -type d -exec chmod 755 {} \;

        # ownership - img - upload
        chown -R root:www-data '/var/www/webroot/img'
        chmod -R 770           '/var/www/webroot/img'

        # sql - access/database
        mysql -u root < '/var/www/sql/access.sql'
        mysql -u root < '/var/www/sql/database.sql'

    fi
    # app |


    # | system
    if [ -d '/tmp/system' ]; then

        # remove - existing
        [ -d '/opt/system' ] && rm -rf '/opt/system'

        # set - permission(s)
        chown -R root:root '/tmp/system'
                      find '/tmp/system' -type f -exec chmod 644 {} \;
                      find '/tmp/system' -type d -exec chmod 755 {} \;

        # move - config(s)
        mv -v '/tmp/system/etc/apache2/sites-enabled/000-default.conf'  '/etc/apache2/sites-enabled/000-default.conf'
        mv -v '/tmp/system/etc/ssh/ssh_config'                          '/etc/ssh/ssh_config'
        mv -v '/tmp/system/etc/ssh/sshd_config'                         '/etc/ssh/sshd_config'

        # remove - tmp/system
        rm -rf '/tmp/system'

        # restart - services
        service apache2 restart
        service ssh     restart

    fi
    # system |




#
#   %(#.0)?-
#
