#!/bin/bash
#
#   curl - test - ajax - img - upload - 200
#




    # variable(s)
    miv_curl="--verbose"
    miv_object='img'
    miv_method='upload'
    miv_data="id_url=0"
    miv_url="build-miv/api.php?object=$miv_object&method=$miv_method"

    # curl
    curl "$miv_curl"                                    \
        -F  "file=@test-ajax-img-upload-200.jpg"        \
        -F  "$miv_data"                                 \
        "$miv_url"                                      \
        $@




#
#   curl - test - ajax - img - upload - 200
#
