/** | create - table - url_has_img **/




    -- MySQL Script generated by MySQL Workbench
    -- Sat 16 Jan 2016 16:42:12 AEDT
    -- Model: New Model    Version: 1.0
    -- MySQL Workbench Forward Engineering

    SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
    SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
    SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

    -- -----------------------------------------------------
    -- Schema miv
    -- -----------------------------------------------------

    -- -----------------------------------------------------
    -- Schema miv
    -- -----------------------------------------------------
    CREATE SCHEMA IF NOT EXISTS `miv` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
    USE `miv` ;

    -- -----------------------------------------------------
    -- Table `miv`.`url_has_img`
    -- -----------------------------------------------------
    DROP TABLE IF EXISTS `miv`.`url_has_img` ;

    CREATE TABLE IF NOT EXISTS `miv`.`url_has_img` (
      `id_url` INT NOT NULL,
      `id_img` INT NOT NULL,
      PRIMARY KEY (`id_url`, `id_img`),
      INDEX `fk_url_has_img_img_idx` (`id_img` ASC),
      INDEX `fk_url_has_img_url_idx` (`id_url` ASC),
      CONSTRAINT `fk_url_has_img_url`
        FOREIGN KEY (`id_url`)
        REFERENCES `miv`.`url` (`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
      CONSTRAINT `fk_url_has_img_img`
        FOREIGN KEY (`id_img`)
        REFERENCES `miv`.`img` (`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


    SET SQL_MODE=@OLD_SQL_MODE;
    SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
    SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




/** create - table - url_has_img | **/
