 /** | create - table - miv - msg **/




    -- MySQL Script generated by MySQL Workbench
    -- Sun 13 Dec 2015 18:29:14 AEDT
    -- Model: New Model    Version: 1.0
    -- MySQL Workbench Forward Engineering

    SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
    SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
    SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

    -- -----------------------------------------------------
    -- Schema miv
    -- -----------------------------------------------------

    -- -----------------------------------------------------
    -- Schema miv
    -- -----------------------------------------------------
    CREATE SCHEMA IF NOT EXISTS `miv` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
    USE `miv` ;

    -- -----------------------------------------------------
    -- Table `miv`.`msg`
    -- -----------------------------------------------------
    DROP TABLE IF EXISTS `miv`.`msg` ;

    CREATE TABLE IF NOT EXISTS `miv`.`msg` (
      `id` INT NOT NULL AUTO_INCREMENT,
      `code` INT(3) NOT NULL,
      `msg` VARCHAR(256) NOT NULL,
      `date_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (`id`))
    ENGINE = InnoDB;


    SET SQL_MODE=@OLD_SQL_MODE;
    SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
    SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




/** create - table - miv - msg | **/
