/** | create - table - img **/




    -- MySQL Script generated by MySQL Workbench
    -- Thu 14 Jan 2016 19:58:32 AEDT
    -- Model: New Model    Version: 1.0
    -- MySQL Workbench Forward Engineering

    SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
    SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
    SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

    -- -----------------------------------------------------
    -- Schema miv
    -- -----------------------------------------------------

    -- -----------------------------------------------------
    -- Schema miv
    -- -----------------------------------------------------
    CREATE SCHEMA IF NOT EXISTS `miv` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
    USE `miv` ;

    -- -----------------------------------------------------
    -- Table `miv`.`img`
    -- -----------------------------------------------------
    DROP TABLE IF EXISTS `miv`.`img` ;

    CREATE TABLE IF NOT EXISTS `miv`.`img` (
      `id` INT NOT NULL AUTO_INCREMENT,
      `id_url` INT NOT NULL,
      `path` VARCHAR(4096) NOT NULL,
      `mime` VARCHAR(255) NOT NULL,
      `size` INT NOT NULL,
      `date_created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (`id`),
      INDEX `fk_img_url_idx` (`id_url` ASC),
      CONSTRAINT `fk_img_url`
        FOREIGN KEY (`id_url`)
        REFERENCES `miv`.`url` (`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


    SET SQL_MODE=@OLD_SQL_MODE;
    SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
    SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




/** create - table - img | **/
